### PR TITLE
Add dark screenshot

### PR DESCRIPTION
**Pull request by vchernin**
Taken using HighContrastInverse application theme set in GNOME Tweaks. Adwaita-dark did not theme consistently.
Screenshot licensed under CC BY 4.0.

Follow up to #3.
Further screenshot discussion: https://github.com/tenacityteam/tenacity/issues/163 https://github.com/tenacityteam/tenacity/pull/426

### CODE REVIEW

**Comment by vchernin** [comment]
Hm, I have never actually kept a GPG keypair around for anything. I guess I could make one, or maybe if it's alright to make 2 commits (one for readme and one for the image) using GitHub's web interface (very high tech I know).

**Comment by SFR-git** [comment]
You don't need a PGP key to sign off your commits: just configure `user.name` and `user.email` then `git commit -s`.

**Comment by Semisol** [comment]
A PGP key but still will be useful in my opinion if you want to sign your commits and other stuff.

**Comment by Semisol** [comment]
Do you mind if I commit to your tree with a readme edit?

**Comment by vchernin** [comment]
> You don't need a PGP key to sign off your commits: just configure user.name and user.email then git commit -s.

As far as I can tell this doesn't fully work. The commit is signed which passes the first check, but the second check seems to want an actual PGP key to be used.

I ran into some issues trying to generate a GPG key on Fedora Silverblue. Likely a sandboxing issue, the password step seems to be the problem. I'm sure I can make it work, but it might require some more learning.

> Do you mind if I commit to your tree with a readme edit?

Honestly it's probably easier to just use your own tree, faster than waiting for me to get GPG working at least. Feel free to commit the image yourself.

**Comment by Semisol** [comment]
You don't have to use GPG yet unless you commit to master branches, but it's encouraged. Merge commits/rebasing on the CLI will automatically sign it with my own key.

**Comment by vchernin** [comment]
> You don't have to use GPG yet unless you commit to master branches, but it's encouraged. Merge commits/rebasing on the CLI will automatically sign it with my own key.

So if this PR is pointed to another branch merging wouldn't be blocked? I would do so but this repo only has a master branch.

**Comment by Semisol** [comment]
> So if this PR is pointed to another branch merging wouldn't be blocked? I would do so but this repo only has a master branch.

Well you might be misunderstanding me, but when we merge this commit it will be signed with our key so you don't have to worry.

**Comment by vchernin** [comment]
Got it, thanks for the help.

In the meantime I got GPG to generate keys finally.

**Comment by Semisol** [comment]
And yes, it signed the commit:
image

**Pull request merged**
